export const ar = {
    loginFormTxt: 'تسجيل الدخول',
    forgetPwpTxt: 'هل نسيت كلمة المرور؟',
    lblUsername: 'اسم المستخدم',
    usernameRequired: 'بالرجاء كتابة اسم المستخدم!',
    lblPwp: 'كلمة المرور',
    loginTitleTxt: 'تسجيل الدخول',
    loginSuccessTxt: 'تم تسجيل الدخول بنجاح',
    loginFailTxt: 'تعذرت عملية تسجيل الدخول بالرجاء المحاولة مرة اخرى',
    transactionsTxt: 'اجمالي التحويلات',
    totTxt: 'الاجمالي',
    mostUserTxt: 'الاعضاء الاكثر تحويلا',
    totMonthSales: 'اجمالي المبيعات للشهر',
    totWeekSales: 'اجمالي المبيعات للاسبوع',
    totMonthProfit: 'اجمالي الارباح للشهر',
    totWeekProfit: 'اجمالي الارباح للاسبوع',
    monthSalesTxt: 'مبيعات الشهر',
    weekSalesTxt: 'مبيعات الاسبوع',
    monthCompSalesTxt: 'مبيعات كل شركة للشهر',
    weekCompSalesTxt: 'مبيعات كل شركة للاسبوع',
    userMonthOrderTxt: 'طلبات الاعضاء للشهر',
    userweekOrderTxt: 'طلبات الاعضاء للاسبوع',
}